apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-auth-service
  labels:
    k8s-app: demo-auth-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: demo-auth-service
  template:
    metadata:
      labels:
        k8s-app: demo-auth-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: auth-service
        image: electroma/ingress-demo-authsvc-amd64:0.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demo-auth-service
  labels:
    k8s-app: demo-auth-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    k8s-app: demo-auth-service
